module Wikiwiki
  module Auth
    class ApiKey
      attr_reader api_key_id: String
      attr_reader secret: String

      def initialize: (api_key_id: String, secret: String) -> void

      def endpoint: () -> String

      def request_body: () -> Hash[Symbol, String]
    end
  end
end
