module Wikiwiki
  module Auth
    class Password
      attr_reader password: String

      def initialize: (password: String) -> void

      def endpoint: () -> String

      def request_body: () -> Hash[Symbol, String]
    end
  end
end
