module Wikiwiki
  VERSION: String

  class Error < StandardError
  end

  class RateLimitError < Error
  end

  class ContentIntegrityError < Error
  end

  class APIError < Error
  end

  class AuthenticationError < APIError
  end

  class ResourceNotFoundError < APIError
  end

  class ServerError < APIError
  end
end
