module Wikiwiki
  class CLI
    module Commands
      module Attachment
        class List < Base
          def call: (
            page_name: String,
            ?out: IO,
            ?err: IO,
            ?wiki_id: String?,
            ?api_key_id: String?,
            ?secret: String?,
            ?password: String?,
            ?json: bool,
            ?verbose: bool,
            ?debug: bool
          ) -> void
        end

        class Show < Base
          def call: (
            page_name: String,
            file_name: String,
            ?out: IO,
            ?err: IO,
            ?wiki_id: String?,
            ?api_key_id: String?,
            ?secret: String?,
            ?password: String?,
            ?json: bool,
            ?verbose: bool,
            ?debug: bool
          ) -> void
        end

        class Get < Base
          def call: (
            page_name: String,
            file_name: String,
            ?directory: String?,
            ?force: bool,
            ?out: IO,
            ?err: IO,
            ?wiki_id: String?,
            ?api_key_id: String?,
            ?secret: String?,
            ?password: String?,
            ?verbose: bool,
            ?debug: bool
          ) -> void
        end

        class Put < Base
          def call: (
            page_name: String,
            file_path: String,
            ?name: String?,
            ?force: bool,
            ?out: IO,
            ?err: IO,
            ?wiki_id: String?,
            ?api_key_id: String?,
            ?secret: String?,
            ?password: String?,
            ?verbose: bool,
            ?debug: bool
          ) -> void
        end

        class Delete < Base
          def call: (
            page_name: String,
            file_name: String,
            ?out: IO,
            ?err: IO,
            ?wiki_id: String?,
            ?api_key_id: String?,
            ?secret: String?,
            ?password: String?,
            ?verbose: bool,
            ?debug: bool
          ) -> void
        end
      end
    end
  end
end
