module Wikiwiki
  class API
    attr_reader logger: Logger
    attr_reader token: String

    def initialize: (wiki_id: String, auth: Auth::Password | Auth::ApiKey | Auth::Token, logger: Logger, ?rate_limiter: RateLimiter) -> void

    def get_pages: () -> Hash[String, Array[Hash[String, String]]]

    def get_page: (encoded_page_name: String) -> Hash[String, String]

    def put_page: (encoded_page_name: String, source: String) -> void

    def get_attachments: (encoded_page_name: String) -> Hash[String, Hash[String, Hash[String, untyped]]]

    def get_attachment: (encoded_page_name: String, encoded_attachment_name: String, ?rev: String?) -> Hash[String, untyped]

    def put_attachment: (encoded_page_name: String, attachment_name: String, encoded_content: String) -> void

    def delete_attachment: (encoded_page_name: String, encoded_attachment_name: String) -> void

    private

    def authenticate: (Auth::Password | Auth::ApiKey | Auth::Token auth) -> String

    def log_token_expiry: (String token) -> void

    def parse_json_response: (Net::HTTPResponse response) -> Hash[String, untyped]

    def request: (Symbol method, URI::HTTPS uri, ?body: Hash[String, String]?, ?authenticate: bool) -> Net::HTTPResponse

    def log_request: (Symbol method, URI::HTTPS uri, Net::HTTPRequest request) -> void

    def log_response: (Net::HTTPResponse response) -> void

    attr_reader wiki_id: String
  end
end
