module Wikiwiki
  class Wiki
    attr_reader logger: Logger

    def initialize: (wiki_id: String, auth: Auth::Password | Auth::ApiKey | Auth::Token, ?rate_limiter: RateLimiter, ?logger: Logger) -> void

    def token: () -> String

    def url: () -> URI::HTTPS

    def page_names: () -> Array[String]

    def page: (page_name: String) -> Page

    def update_page: (page_name: String, source: String) -> void

    def attachment_names: (page_name: String) -> Array[String]

    def attachment: (page_name: String, attachment_name: String, ?rev: String?) -> Attachment

    def add_attachment: (page_name: String, attachment_name: String, content: String) -> void

    def delete_attachment: (page_name: String, attachment_name: String) -> void

    private

    attr_reader api: API
    attr_reader wiki_id: String
  end
end
